var n=Object.defineProperty;var u=(a,t,s)=>t in a?n(a,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):a[t]=s;var r=(a,t,s)=>u(a,typeof t!="symbol"?t+"":t,s);import{j as i}from"./ConfirmationContext-_sHM_c2k.js";import{r as m}from"./vendor-CfxRerCp.js";import p from"./Error-CrCgpK4W.js";import"./Navbar-BvdoVYAz.js";import"./axiosInstance-tLBeUCrM.js";class x extends m.Component{constructor(){super(...arguments);r(this,"state",{hasError:!1,errorStatus:void 0,errorMessage:void 0})}static getDerivedStateFromError(s){let e,o;return s!=null&&s.response?(e=s.response.status,o=s.response.statusText||s.message):s!=null&&s.status?(e=s.status,o=s.message):(e=void 0,o=(s==null?void 0:s.message)||"An unexpected error occurred."),{hasError:!0,errorStatus:e,errorMessage:o}}componentDidCatch(s,e){console.error("Caught by ErrorBoundary:",s,e)}render(){const{hasError:s,errorStatus:e,errorMessage:o}=this.state;return s?i.jsx(p,{status:e??500,message:o}):this.props.children}}export{x as ErrorBoundary};
